# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Battle Map Studio
email: support@harken.studio
description: >- # this means to ignore newlines until "baseurl:"
  Battle Map Studio is a playful map editor and RPG sandbox that makes world building fun, simple, and social. 
  Use a variety of practical and amusing tools to paint forests and rivers, generate mountains, and construct houses. 
  Then, populate your world with characters and creatures to set the stage for playing RPG campaigns.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: battlemapstudio
github_username:  harkenstudio

# Build settings
theme: minima
#remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

domain: harken-studio.github.io/BattleMapStudio_Public/       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://harken-studio.github.io/BattleMapStudio_Public/ # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /docs/      # place folder name if the site is served in a subfolder

gem "github-pages", group: :jekyll_plugins
